### PR TITLE
Page stepper

### PR DESCRIPTION
**Pull request by jlangy**
### Please check if the PR fulfills these requirements:

- [ ] After these changes, the app was run and still works as expected
- [x] Tests for these changes were added (if applicable)
- [ ] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
chore

### CODE REVIEW

**Review by bryce-mcmath — COMMENTED** [review]
Will the attributes and listeners still be applied to that created tag? Did you test that?

**Comment by jlangy** [comment]
I tested the tag and the slot content, good point though I will extend the testing to make sure any attributes and listeners come through

**Comment by jlangy** [comment]
I added some tests for that (linted the pagestepper too), it's using some vue magic with fallthrough attributes which looks odd, I put in the comment to the docs explaining why it works though.

 The reason I switched from `createElement` is it changed to a global import (instead of the first arg to the render function) in vue-3, which was causing issues related to vue being imported twice with jest and storybook.

**Review by harrymaynard-maximus — APPROVED** [review]
Looks good.

**Review by bryce-mcmath — APPROVED** [review]
Very nice!

**Pull request merged**
