### PR TITLE
Add Cypress values to RegionSelect, CountrySelect

### PR DESCRIPTION
**Pull request by stephanieharrison-maximus**
### Please check if the PR fulfills these requirements:

- [X] After these changes, the app was run and still works as expected
- [] Tests for these changes were added (if applicable) 
- [X] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
Adds data-cy values to the RegionSelect and CountrySelect components for Cypress testing.

### Additional Notes:
I didn't add tests due to the minor-ness of the change, but I can if desired.

### CODE REVIEW

**Review by bryce-mcmath — APPROVED** [review]
Looks good. When you're done and you've published a patch version, please checkout the v3 branch and merge main into it, then fix the conflicts if there are any and publish an alpha version of the v3 branch

**Comment by cyrilbravo** [comment]
Changes looks good. Approved :)

**Review by cyrilbravo — APPROVED** [review]

**Review by bryce-mcmath — APPROVED** [review]
Looks good! Thanks for fixing that

**Comment by cyrilbravo** [comment]
The new commits looks good. Nice job!

**Pull request merged**
