### PR TITLE
update missing stories

### PR DESCRIPTION
**Pull request by jlangy**
### Please check if the PR fulfills these requirements:

- [ ] After these changes, the app was run and still works as expected
- [ ] Tests for these changes were added (if applicable)
- [ ] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
chore
### Additional Notes:
update any missing stories

### CODE REVIEW

**Review by bryce-mcmath — APPROVED** [review]
Looks good. What's causing the Github actions to still be failing?

**Review by harrymaynard-maximus — APPROVED** [review]
Looks good.

**Comment by jlangy** [comment]
Taking a look at the CI bug, the `npm ci` step is failing when trying to run `git ls-remote` on bcgov/bootstrap-theme, not sure why yet

**Comment by harrymaynard-maximus** [comment]
Try changing the "package.json" dependency entry to this format:
```
"depName": "user/repo#tag",
```

**Pull request merged**
